### ISSUE TITLE
Travis Build Failing due to libc6

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#30]
This started when I made changes yesterday. I reverted back and the issue persisted, and also the change I made had nothing to do with this. 

Tensorflow backend fails to load due to missing libc6. I checked out some conversations, and it seems that it might have to do something with versions. Resolving now. 
```

Traceback (most recent call last):
  File "./test_script.py", line 1, in <module>
    from autonomio.commands import data, train, test
  File "/home/travis/build/autonomio/core-module/autonomio/__init__.py", line 3, in <module>
    from train_new import kuubio
  File "/home/travis/build/autonomio/core-module/autonomio/train_new.py", line 7, in <module>
    from transform_data import transform_data
  File "/home/travis/build/autonomio/core-module/autonomio/transform_data.py", line 6, in <module>
    from y_transform import y_transform
  File "/home/travis/build/autonomio/core-module/autonomio/y_transform.py", line 2, in <module>
    from keras.utils import np_utils
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/keras/backend/__init__.py", line 73, in <module>
    from .tensorflow_backend import *
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

**Comment by mikkokotila** [comment]
Can you take a look at this Anish? I think it's some pretty basic linux package stuff. Maybe some versions change since we did our last build, and that messed it up.

**Comment by m-anish** [comment]
Is it okay if I have a look tomorrow evening, or day-after-tomorrow morning?

**Comment by mikkokotila** [comment]
Totally yea. Thanks!~

**Comment by m-anish** [comment]
This might be an issue with tensorflow. I've opened a ticket on their tracker.

https://github.com/tensorflow/tensorflow/issues/9838

**Comment by yaroslavvb** [comment]
BTW, this usually means your system is too old. TensorFlow internal testing is using Ubuntu 16.04, are you on 14.04? It's possible to make it work with older systems by upgrading just glibc, 

http://stackoverflow.com/questions/33655731/error-while-importing-tensorflow-in-python2-7-in-ubuntu-12-04-glibc-2-17-not-f

**Comment by m-anish** [comment]
Dear @yaroslavvb it looks like we are on 16.04 as this line within .travis.yml would suggest.

https://github.com/autonomio/core-module/blob/master/.travis.yml#L2

**Comment by m-anish** [comment]
Hmm. Looks like from the log we are on ubuntu 12.04. Strange! I will check the travis configuration.

**Comment by yaroslavvb** [comment]
Do `ldd --version`. My Ubuntu 14.04 system has 2.19, and looks like TF only needs 2.17

(memory) yaroslav@52:~/git0/pixel-cnn-private$ ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.9) 2.19

**Comment by m-anish** [comment]
It looks as if travis doesn't support 16.04 as of now :( 

https://docs.travis-ci.com/user/ci-environment/

@mikkokotila What do you suggest?

**Comment by yaroslavvb** [comment]
14.04 should be OK. There are quite a few people using 14.04 still

**Comment by mikkokotila** [comment]
Hey, and thanks very much for @yaroslavvb this. I'm sorry I was away for a couple of days. I think 14.04 is totally fine for our core and it will work out of the box, but for the container version we would have to think this through more carefully, as we intentionally avoided the 14.04 base image on docker after giving it a try. I guess if we want to keep using Travis CI in this context, we have no other option that going through the hoops of setting up the container again but now on 14.04.

Unless you disagree @m-anish I'll create an issue for that...and assign to you _()_

**Comment by mikkokotila** [comment]
this is resolved (sometime time ago I believe).
