### ISSUE TITLE
Travis build failing on trusty

### ISSUE THREAD

**Issue by m-anish** [autonomio/core-module#33]
This is from the travis log. Does this error make sense to you? 

```
Using TensorFlow backend.

Traceback (most recent call last):

  File "./test_script.py", line 16, in <module>

    tr = train(1,'neg',temp,dims=1)

  File "/home/travis/build/m-anish/autonomio/autonomio/commands.py", line 49, in train

    verbose)

  File "/home/travis/build/m-anish/autonomio/autonomio/train_new.py", line 55, in kuubio

    X,Y = transform_data(X,Y,data,flatten,dims)

  File "/home/travis/build/m-anish/autonomio/autonomio/transform_data.py", line 25, in transform_data

    x = x_transform(X,data)

  File "/home/travis/build/m-anish/autonomio/autonomio/x_transform.py", line 28, in x_transform

    x = data[[X]]

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/pandas/core/frame.py", line 2056, in __getitem__

    return self._getitem_array(key)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/pandas/core/frame.py", line 2100, in _getitem_array

    indexer = self.loc._convert_to_indexer(key, axis=1)

  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer

    raise KeyError('%s not in index' % objarr[mask])

KeyError: '[1] not in index'
```

**Comment by mikkokotila** [comment]
Yes, this looks like it's coming from Pandas, and it seems that the only line of code where we are calling Pandas key indexing is: 

x = data[[X]]

I'm not sure why it's in double brackets, that's probably causing the problem. Can you try if you try running the same code locally and see if you get the same error, and if yes if the double bracket is the issue. But there is something off with this anyway, as the previous line already creates 'x' and then we seem to create it again? Or am I missing something?

**Comment by m-anish** [comment]
Okay. Will try.

**Comment by mikkokotila** [comment]
Were you able to get over this? Note that this is a pandas error and has nothing to do with env or anything like that.

**Comment by mikkokotila** [comment]
Do you need any help with this? By the way, this might be a result of...

![83f78e62feb95acc85d000aaf6350d23](https://user-images.githubusercontent.com/7943188/26985090-ae4b8e06-4d4a-11e7-860c-07ffb349a662.jpg)

**Comment by mikkokotila** [comment]
There was a couple of bugs that I had to go through to get back to green. It was probably something to do with pandas version changing or something, as we had to move in to a far more verbose way of slicing the dataframe. But now we're back to green! :)
