### ISSUE TITLE
jinja2 is not installed in setup

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/core-module#77]
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mikko/dev/autonomio_bug/lib/python2.7/site-packages/autonomio/__init__.py", line 3, in <module>
    from train_new import kuubio
  File "/Users/mikko/dev/autonomio_bug/lib/python2.7/site-packages/autonomio/train_new.py", line 9, in <module>
    from plots import accuracy
  File "/Users/mikko/dev/autonomio_bug/lib/python2.7/site-packages/autonomio/plots.py", line 4, in <module>
    import mpld3
  File "/Users/mikko/dev/autonomio_bug/lib/python2.7/site-packages/mpld3/__init__.py", line 43, in <module>
    from ._display import *
  File "/Users/mikko/dev/autonomio_bug/lib/python2.7/site-packages/mpld3/_display.py", line 4, in <module>
    import jinja2
ImportError: No module named jinja2

**Comment by konchokdolma** [comment]
Fixed
